### ISSUE TITLE
Start Quality Assurance guide

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#14]
The idea here is to have the first version of the quality assurance guide. In my Office Hour me and @rpattath came up with a plan for it so this should be put into public more accessible document than the "Community Open Session Minutes" document.

**Comment by isabelcosta** [comment]
@rpattath do you want to do this or can I go forward with this?
The idea here is to put into markdown format what we came up with in my office hour regarding Quallity Assurance workflows.

**Comment by rpattath** [comment]
@isabelcosta yes I can take this up.
