### ISSUE TITLE
Design a background image for our Medium Blog

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#15]
## Problem

Currently, our Medium Blog is lacking a background image which can make the Blog look a bit boring.
So the idea here is to design an asset that will look good on our Medium Publication.
We want something to enhance the title of the publication.

Be as creative as you want, having in mind the redimensioning of the page, something that can be flattering no matter the size of the page.

You can get the AnitaB.Org Brand Guidelines [here in this message](https://anitab-org.zulipchat.com/#narrow/stream/216323-design/topic/Branding.20Guidelines/near/182850387).

## Current visual

![image](https://user-images.githubusercontent.com/11148726/88574076-a3eaaa80-d039-11ea-82bb-283fbb11be3e.png)

## References

- Cover image submission guidelines: https://help.medium.com/hc/en-us/articles/360053012914

**Comment by nandini45** [comment]
@isabelcosta can i work on it ?

**Comment by isabelcosta** [comment]
Sure @nandini45 :) Please update us within 3 days.

**Comment by nandini45** [comment]
@isabelcosta  can  u tell me any idea that you had in mind for the background image?
 i will share what ideas i had and what i did

**Comment by nandini45** [comment]
does the open source community has any motto that we represent or the same Anitab-org ?

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/88854275-a6eac400-d20e-11ea-8aea-c516556ba1cc.png)

![image](https://user-images.githubusercontent.com/62046625/88854343-c7b31980-d20e-11ea-83b2-a60178193624.png)

@isabelcosta  i had 2 ideas that either we can draw human illustrations showing diversity 
or using our logo color sketch females showing different womens of colors representing diversity in women

**Comment by isabelcosta** [comment]
@nandini45 be as creative as you want :D I love the second image with so many colors and differences shown.
The first image does not say much to me. I just have a little pointer, the log of anitab.org does not need to contain "Systers" since the community brand does no limit itself just to Systers but to the AnitaB.org brand as a whole, even if targeting Open Source.

**Comment by isabelcosta** [comment]
@nandini45 I briefly tried your 2nd image and it looks super nice and fits very nicely 👏  the logo is the only thing that I see could be improved

**Comment by nandini45** [comment]
@isabelcosta  i may need some time to sketch the one out and make some changes.. i will update you as soon as I can

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/89110590-da755a80-d469-11ea-9a7e-75322d9c7f29.png)

![image](https://user-images.githubusercontent.com/62046625/89110600-e82ae000-d469-11ea-9551-79e4c6b87132.png)
 
which one do u like?

@isabelcosta 
i had one more idea i am sketching that out 
i will also share that

**Comment by nandini45** [comment]
i had a question @isabelcosta  that if we show men in the photo will it be correct?
because the motto says women transform n so

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/89111335-40fe7680-d472-11ea-9762-2a952c993d1b.png)

**Comment by isabelcosta** [comment]
@nandini45 I like this one better. Feels more natural, the last one shows the square that contains the text, and the first does not feel to me related with sense of community. Feel free to share this with the community to get more feedback if you'd like. I am happy with option 2 :)

> ![image](https://user-images.githubusercontent.com/62046625/89110600-e82ae000-d469-11ea-9551-79e4c6b87132.png)

**Comment by isabelcosta** [comment]
@nandini45 can you please provide the image without the middle part (title and subtitle), because that comes from Medium page itself. Can you provide the asset without the part in the middle?

**Comment by nandini45** [comment]
yes @isabelcosta
 i am on the verge of finishing the design i will remove the middle part as u said

**Comment by isabelcosta** [comment]
It's ok @nandini45 ! Thank you for the update :)

**Comment by Pranjal9999999** [comment]
If this is still available I would like to work on it.

**Comment by isabelcosta** [comment]
@Pranjal9999999 I think @nandini45 is still working on this. Correct me if I'm wrong @nandini45 :)

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/92153500-022d5900-ee42-11ea-8ffe-228d4088b998.png)

@isabelcosta  this is half of the image i am working on their facial features. can u tell me any other improvement which i can make ?

**Comment by nandini45** [comment]
i am working
@isabelcosta

**Comment by nandini45** [comment]
please do ignore their facial expression i wanted to know a review so i just sent the image

**Comment by nandini45** [comment]
@isabelcosta  the image is ready.
 should i open a pull request or? share the image here?

**Comment by nandini45** [comment]
i asked the design team for review they liked it. i made some changes and finalized it i will again ask their review today

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/93669486-3cd5f900-fab2-11ea-9bfc-ce449bf5a58f.png)

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/93669742-e79ae700-fab3-11ea-9fae-e63c183f60e6.png)

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/93669770-131dd180-fab4-11ea-81a6-30803498df4d.png)

**Comment by nandini45** [comment]
https://www.figma.com/file/UR7rRDUF4zPzVZoiVu8SyE/blog_design?node-id=0%3A1

**Comment by nandini45** [comment]
https://www.figma.com/file/UR7rRDUF4zPzVZoiVu8SyE/blog_design?node-id=0%3A1

**Comment by nandini45** [comment]
in the image you may see some mistakes but if you open the link review 
 you can see the actual file.
 if you think its good shall i open a PR?

**Comment by nandini45** [comment]
@isabelcosta ??

**Comment by isabelcosta** [comment]
@nandini45 you can also upload on the Google Drive folder shared between us and link it in the Our Blog document :)

One tiny question, does this image follow AnitaB.org Design Guidelines? 
![image](https://user-images.githubusercontent.com/11148726/94184230-82703880-fe9b-11ea-8e54-d88943d74817.png)

**Comment by nandini45** [comment]
Yes it does follows all guidelines but I don't know maybe for some reference if you can recommend someone to me.. 
Btw I did ask the design team for reference they approved of it..!

**Comment by nandini45** [comment]
@isabelcosta

**Comment by isabelcosta** [comment]
that is good image :) You can put it on google drive and let me know and I put in the Medium publication :)
Also feel free to create a PR, and add the link to the image, perhaps even render the image in the `our-blog.md`. Let me know if you have any doubt

**Comment by nandini45** [comment]
nope thanks
https://drive.google.com/drive/folders/1r3qrkaCcSRWqJTE50tB7jzXVMnCbEab9?zx=se7hfltre7x8
 here is the drive link 
and i will create a PR too
@isabelcosta

**Comment by isabelcosta** [comment]
@nandini45 added it to medium publication :) https://medium.com/anitab-org-open-source

**Comment by nandini45** [comment]
@isabelcosta  i had a question do u like the images ??
maybe i should like reduce the size something??

**Comment by isabelcosta** [comment]
@nandini45 I really like it :) It's a very nice image. We can always improve it, but for the first version, I think it looks very nice :)

**Comment by isabelcosta** [comment]
@nandini45 feel free to add this image link to the repository so that it's clear you came up with this image. We are already using it on Medium, but I think it would be nice if we would have it as well in the document about our blog on this repository. Can you submit a pull request to add the image in `our-blog.md` file?

**Comment by nandini45** [comment]
Sure Isabel.
 I will do it by today
