### ISSUE TITLE
Create a document to start documenting Design related content

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#16]
## Description

We need a document to have information related to Design within our organization. For example, we could have a link to the AnitaB.org Brand Guidelines, among other things.

**Comment by siddhipandare** [comment]
I think design team would know which guidelines to add and information about creating design mocks better. I can help with compiling and creating the .md file. 
@anitab-org/design-team anyone would like to work on this?

**Comment by sakshi1499** [comment]
Yes we have a document for the same purpose, it just needs editing.

**Comment by 19-pragya** [comment]
can i work on this??

**Comment by ayushi1109** [comment]
could you please assign this task to me??

**Comment by nandini45** [comment]
@19-pragya @ayushi1109  this issue is not open for contribution.. look for a issue with th label available

**Comment by isabelcosta** [comment]
Fixed w/ https://github.com/anitab-org/documentation/pull/48
