### ISSUE TITLE
Create document about our Zulip

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#17]
## Description

An initial version of this just needs to contain information about our Zulip. It can include the main streams we use and the project's streams. Explain what each stream is used for.

Adding emojis to each channel could be fun :)

**Comment by kakabisht** [comment]
I could take this up, if it's okay?

**Comment by SanketDG** [comment]
@kakabisht is #18 your PR?

**Comment by 19-pragya** [comment]
Can i work on this if its available?

**Comment by SanketDG** [comment]
@kakabisht You still on this?

**Comment by kakabisht** [comment]
Hi @SanketDG  I had submitted the file about 10 days ago and was waiting for further modifications from @isabelcosta.
[This is the pull request link](https://github.com/anitab-org/documentation/pull/19)

**Comment by isabelcosta** [comment]
fixes by #19
