### ISSUE TITLE
Add link to #documentation stream on Zulip to ways-to-contribute.md document

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#27]
## Description

This file [ways-to-contribute.md](https://github.com/anitab-org/documentation/blob/master/ways-to-contribute.md) has the text referring to #documentation stream on Zulip. We could have a link to it, like other streams in the same document have.

## Why

This helps newcomers reading the document have direct access to the stream

## Acceptance Criteria

- [ ] Add the link to #documentation stream from Zulip

**Comment by nlok5923** [comment]
@isabelcosta i would like to work on this issue.

**Comment by isabelcosta** [comment]
@nlok5923 sure :) Will assign it to you!

**Comment by nlok5923** [comment]
@isabelcosta please can you help me to find zulip stream link
