### ISSUE TITLE
Create Pull Request lifecycle document

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#31]
## Description

We already follow a workflow for a pull request, however, we don't have this documented anywhere yet.
@anitab-org/admins worked on a text-based version, that I think we could already share it, and then improve upon it.

This is sort of related to #3 issue, however, we could consider this as a subtask of that issue, we could proceed until we have more content to add.

**Comment by unnati914** [comment]
could i work on this?

**Comment by isabelcosta** [comment]
sorry @unnati914 i think i forgot to link this issue to my PR, but this was already solved by https://github.com/anitab-org/documentation/pull/50
