### ISSUE TITLE
Grammatical errors 

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/documentation#33]
### Describe
There are some grammatical errors in the [ways-to-contribute.md](https://github.com/anitab-org/documentation/blob/master/ways-to-contribute.md) and [quality-assurance.md](https://github.com/anitab-org/documentation/blob/master/quality-assurance.md) files.

### Expected Behavior
All of the below mentioned grammatical errors needs to be fixed.

### Steps to reproduce
1. Go to [ways-to-contribute.md](https://github.com/anitab-org/documentation/blob/master/ways-to-contribute.md).
2.  See errors in the description.

### Screenshots
ways-to-contribute.md
![doc-issue-1](https://user-images.githubusercontent.com/54268438/106365192-e7f89800-6359-11eb-887c-bc5a1717bf96.JPG)
![doc-issue-2](https://user-images.githubusercontent.com/54268438/106365194-e9c25b80-6359-11eb-9edb-97fef8e10c47.JPG)
![doc-issue-3](https://user-images.githubusercontent.com/54268438/106365198-ec24b580-6359-11eb-8a74-036d89b27b49.JPG)
![doc-issue-4](https://user-images.githubusercontent.com/54268438/106365199-edee7900-6359-11eb-8676-104a79d30dd1.JPG)

quality-assurance.md
![doc-issue-5](https://user-images.githubusercontent.com/54268438/106365203-f2b32d00-6359-11eb-8aa4-4df898a1f8f2.JPG)
![doc-issue-6](https://user-images.githubusercontent.com/54268438/106365350-feebba00-635a-11eb-9dc3-9ca4ca0ab441.JPG)
![doc-issue-7](https://user-images.githubusercontent.com/54268438/106365351-00b57d80-635b-11eb-93cb-d2a53ce18564.JPG)

**Comment by Rahulm2310** [comment]
@isabelcosta Could you please confirm and assign me this issue. Thanks 🙂

**Comment by isabelcosta** [comment]
@Rahulm2310 yeeees! Thank you for spotting those and raising an issue for it!
