### ISSUE TITLE
Feat: Create MAINTAINER_GUIDELINES.md for projects to refer to.

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/documentation#42]
### Is your feature request related to a problem? Please describe.
Projects needs to have one source of truth where they can refer to `Maintainer Guidelines` instruction on wiki page. 

### Describe the solution you'd like
Create MAINTAINER_GUIDELINES.md template.

### Describe alternatives you've considered
NA

### Additional context
* Content for the template can be found [here](https://github.com/anitab-org/anitab-org.github.io/wiki/Maintainer-Guidelines)

**Comment by Jasmine9003** [comment]
Can I take up this issue?

**Comment by mtreacy002** [comment]
Sure, @P-riyanka-prasad , I'll assign you to this as you claim this first 😉.

**Comment by aditisingh2412** [comment]
Can I work on this issue?

**Comment by isabelcosta** [comment]
will unassign due to lack of response @P-riyanka-prasad 
@aditisingh2412 are you still interested in this issue?

**Comment by Jayita10** [comment]
I want to work on this issue. Please assign me

**Comment by isabelcosta** [comment]
its yours now @Jayita10 :)

**Comment by Jayita10** [comment]
I have opened a PR, Please review @isabelcosta :)
