### ISSUE TITLE
Feat: Create FORK_CLONE_REMOTE.md for all projects repo to refer to

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/documentation#43]
### Is your feature request related to a problem? Please describe.
Currently projects under anita-org has their own copy of `Fork, Clone & Remote` instructions on wiki page. These pages are redundant because we only need one page that all projects can refer to.
 
### Describe the solution you'd like
Create FORK_CLONE_REMOTE.md template.

### Describe alternatives you've considered
NA

### Additional context
Make sure you remove any project specific references.

<img width="488" alt="Screen Shot 2021-03-19 at 9 25 49 am" src="https://user-images.githubusercontent.com/29667122/111705699-38d63880-8895-11eb-8761-bcc40abe0cb5.png">

**Comment by Jasmine9003** [comment]
Can I take up this issue @mtreacy002

**Comment by mtreacy002** [comment]
Sure, @Jasmine9003 . This issue is now yours 😉. Thanks for picking up the issue 👍.

**Comment by Jasmine9003** [comment]
@mtreacy002 I have created a PR for this issue, kindly review it once.
