### ISSUE TITLE
Feat: Create DESIGN_CONTRIBUTION_GUIDELINES.md for projects to refer to.

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/documentation#44]
### Is your feature request related to a problem? Please describe.
Projects needs to have one source of truth where they can refer to `Design Contribution Guidelines` instruction on wiki page. 

### Describe the solution you'd like
Create DESIGN_CONTRIBUTION_GUIDELINES.md template.

### Describe alternatives you've considered
NA

### Additional context
* Content for the template can be found [here](https://github.com/anitab-org/anitab-org.github.io/wiki/Design-Contributions) 
* Note: remove project specific content

<img width="481" alt="Screen Shot 2021-03-19 at 10 01 18 am" src="https://user-images.githubusercontent.com/29667122/111708505-17c41680-889a-11eb-97e3-52f3b78a4e09.png">

**Comment by Jasmine9003** [comment]
Can I take up this issue? @mtreacy002

**Comment by mtreacy002** [comment]
@Jasmine9003 , you've been assigned to #43 . So, please focus on that issue for now 😉

**Comment by aditisingh2412** [comment]
Can I work on this issue? @mtreacy002

**Comment by mtreacy002** [comment]
Sure, @aditisingh2412 . I'll assign you to this now. Thanks for picking up the issue 😉.

**Comment by aditisingh2412** [comment]
@mtreacy002 I have created a PR for this issue, kindly look to it. And if there are any changes to do, let me know :)
