### ISSUE TITLE
Feat: Create OS_LEADERS.md to list OS Leaders and their roles

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/documentation#45]
### Is your feature request related to a problem? Please describe.
It would be helpful for contributors to know the OS Leaders and their roles on the projects. This way they know who to ping on project specific issue. 

### Describe the solution you'd like
Create a OS_LEADERS.md doc that shows a table below:

| Project | Repositories | Name | Zulip ID | Github ID | Role |
| --- | --- | --- | --- | ---- | ---- |
| Mentorship System | [mentorship-backend](https://github.com/anitab-org/mentorship-backend) | - | - | - | Maintainers |
| | [mentorship-android](https://github.com/anitab-org/mentorship-android) | - | - | - | Design |
| | | - | - | - | Documentation |
| | | - | - | - | Quality Assurance |
| | | - | - | - | Other |
| STEM Diverse TV | [stem-diverse-tv](https://github.com/anitab-org/stem-diverse-tv) | - | - | - | Maintainers |
| | [stem-diverse-tv-cms](https://github.com/anitab-org/stem-diverse-tv-cms) | - | - | - | Design |
| | | - | - | - | Documentation |
| | | - | - | - | Quality Assurance |
| | | - | - | - | Other |
| BridgeInTech | [bridge-in-tech-backend](https://github.com/anitab-org/bridge-in-tech-backend) | - | - | - | Maintainers |
| | [bridge-in-tech-web](https://github.com/anitab-org/bridge-in-tech-web) | - | - | - | Design |
| | | - | - | - | Documentation |
| | | - | - | - | Quality Assurance |
| | | - | - | - | Other |
| Open Source Programs (AnitaB Forms) | [open-source-programs-backend](https://github.com/anitab-org/open-source-programs-backend) | - | - | - | Maintainers |
| | [open-source-programs-web](https://github.com/anitab-org/bridge-in-tech-web) | - | - | - | Design |
| | | - | - | - | Documentation |
| | | - | - | - | Quality Assurance |
| | | - | - | - | Other |
| Community Website | [anitab-org.github.io](https://github.com/anitab-org/anitab-org.github.io) | - | - | - | Maintainers |
| | | - | - | - | Design |
| | | - | - | - | Documentation |
| | | - | - | - | Quality Assurance |
| | | - | - | - | Other |

### Describe alternatives you've considered
NA

### Additional context
List of OS Leaders with their project/role will be taken from the OS Project Pods document which is accessible only to admins and OS Leaders. So, perhaps this issue can only be claimed by an OS Leader.

**Comment by mtreacy002** [comment]
@isabelcosta or @annabauza , can you please confirm whether or not this issue is valid? Thanks

**Comment by isabelcosta** [comment]
@mtreacy002 I just saw this now, but will totally come back to this, in a couple weeks.

**Comment by Jayita10** [comment]
Cam I work on this issue? @isabelcosta

**Comment by Esther-Wavinya** [comment]
Can I work on this? @isabelcosta @mtreacy002

**Comment by isabelcosta** [comment]
This issue is a bit old. At the moment, we don't have an ongoing ambassadors program, so we don't have official OS leaders to fill in this information.
I will close this issue cc @anitab-org/admins 
cc @Jayita10 @Esther-Wavinya
