### ISSUE TITLE
Duplicate word on README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#52]
## Description

There is a typo in the README, the duplicate word in the design guidelines bullet point.

### Update [Required]
- [ ] Remove duplicate `Contributing` word from Design guidelines on README

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation

0.5 hours

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by isabelcosta** [comment]
sure will assign to you @himanshu007-creator
