### ISSUE TITLE
Update test PR guide following most recent mentorship-backend docs change

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#53]
## Description

Update this repository instructions to fetch a contributor's PR: https://github.com/anitab-org/documentation/blob/master/quality-assurance.md#how-to-test-a-pr
You can follow this PR work https://github.com/anitab-org/mentorship-backend/pull/1076

## Mocks

https://github.com/anitab-org/mentorship-backend/pull/1076

### Update [Required]
- [ ] Update test PR guide using info provided in the description

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by StephNathai** [comment]
Hi! Can I work on this?

**Comment by StephNathai** [comment]
Hi @isabelcosta! Can I work on this?

**Comment by StephNathai** [comment]
@isabelcosta Hi, just following up to see if it's ok to grab this one, thanks!

**Comment by isabelcosta** [comment]
Yes @StephNathai ! I will assign to you :)

**Comment by isabelcosta** [comment]
Thank you for tagging me and following up. I had missed this.

**Comment by StephNathai** [comment]
Hi @isabelcosta - my PR is above, please let me know if I need to do anything additional, thank you!
