### ISSUE TITLE
Create meeting document for Mentorship System

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#59]
## Description

As a contributor,
I need information accessible to me about the community (less on Google Drive - more on GitHub),
so that I can learn more about it.

The idea is to post the meeting summaries on here just as we tend to do on Zulip. Therefore making information more transparent and available to people who are not part of our Zulip community.

### Update [Required]
- [ ] A new folder called `meetings` with a markdown file for `mentorship-system`. Most recent meetings should have the summary on the top. 3 summaries should be enough.

### Enhancement to Update [Optional]
- [ ] A README explaining briefly the folder contains meeting summaries

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation

1 h

**Comment by gaurivn** [comment]
Assigning myself as we discussed in today's Mentorship sync-up session.
