### ISSUE TITLE
Research a way for building an apk per Android PR sent

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#6]
# Problem

As of now, if a tester wishes to test an Android PR, they have to run and build the project. This can be cumbersome for a tester.

# Idea

Discover a way to produce apks per pull request.

We could research if we are able to do that with a GitHub Action or something like that, to build an APK per pull request. The same way we have an apk generated for most of Android projects.
Example: Android APK from mentorship-android [apk branch](https://github.com/anitab-org/mentorship-android/tree/apk)

Once this is solved, this can be applied to every Android project of ours.

**Comment by isabelcosta** [comment]
@Techno-Disaster I assigned this to you, but you can ask for help, or have someone helping you here.

**Comment by Techno-Disaster** [comment]
> @Techno-Disaster I assigned this to you, but you can ask for help, or have someone helping you here.

Yes, I already did some work on this. 
If anyone wants to help, I'm considering using diawi. already have a github action to upload to diawi ready. need to integrate with the build scripts now. 

I'm open to any other suggestions.

**Comment by isabelcosta** [comment]
@Techno-Disaster I quickly looked at your Zulip message, but I have not researched the subject much. So I have no suggestions as of now

**Comment by HaripriyaB** [comment]
https://www.diawi.com/ 
I checked about it. But it needs the contributor to upload the whole android project and then the apk will be sent to the tester.

**Comment by HaripriyaB** [comment]
> 
> 
> https://www.diawi.com/
> I checked about it. But it needs the contributor to upload the whole android project and then the apk will be sent to the tester.

But this would take time and I think we need to find a solution to automate it.

**Comment by Techno-Disaster** [comment]
> https://www.diawi.com/
> I checked about it. But it needs the contributor to upload the whole android project and then the apk will be sent to the tester.

yes, as i said i already have a script to upload the app, just need to integrate it with the PR and building process

**Comment by HaripriyaB** [comment]
> 
> 
> > https://www.diawi.com/
> > I checked about it. But it needs the contributor to upload the whole android project and then the apk will be sent to the tester.
> 
> yes, as i said i already have a script to upload the app, just need to integrate it with the PR and building process

How to do that? :

**Comment by Techno-Disaster** [comment]
> > > https://www.diawi.com/
> > > I checked about it. But it needs the contributor to upload the whole android project and then the apk will be sent to the tester.
> > 
> > 
> > yes, as i said i already have a script to upload the app, just need to integrate it with the PR and building process
> 
> How to do that? :

working on it. Don't have time this week tho

**Comment by ayushi1109** [comment]
could you please assign this task to me??

**Comment by Techno-Disaster** [comment]
This issue is done already and merged on flutter repo

**Comment by ayushi1109** [comment]
okie, thankyou !

**Comment by isabelcosta** [comment]
@vj-codes this is done right? For Mentorship Android 🤔

**Comment by vj-codes** [comment]
@isabelcosta yes
