### ISSUE TITLE
Add CODE_OF_CONDUCT and REPORTING_GUIDELINES markdown files to the root

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/documentation#9]
Add CODE_OF_CONDUCT and REPORTING_GUIDELINES to the root folder of this project.
This is important for having a source of truth about our documentation.

Here's examples you can copy: 
- CoC: https://github.com/anitab-org/anitab-org.github.io/blob/develop/docs/code_of_conduct.md
- Reporting Guidelines: https://github.com/anitab-org/anitab-org.github.io/blob/develop/docs/reporting_guidelines.md

**Comment by 19-pragya** [comment]
Can i work on this
